name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Run at 6PM UTC every Monday which is 2 hours after the truemark/aws-cli build
    - cron: '0 18 * * 1'

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ secrets.AWS_ASSUME_ROLE }}"
          aws-region: "us-east-1"
          role-duration-seconds: 7200
      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Setup Buildx Remote Docker
        id: buildx
        uses: truemark/aws-buildx-remote-docker-instance-action@v4
        with:
          security-group-id: "${{ vars.SECURITY_GROUP_ID }}"
          subnet-id: "${{ vars.SUBNET_ID }}"
          instance-profile: "${{ vars.INSTANCE_PROFILE }}"
          region: "us-east-2"
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f Dockerfile \
            -t truemark/aws-ecs-deploy:${{github.run_number}} \
            -t truemark/aws-ecs-deploy:latest \
            .
      - name: Copy ${{github.run_number}} to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-ecs-deploy:${{github.run_number}}"
          dest-image: "docker://public.ecr.aws/truemark/aws-ecs-deploy:${{github.run_number}}"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy latest to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-ecs-deploy:latest"
          dest-image: "docker://public.ecr.aws/truemark/aws-ecs-deploy:latest"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
